language: go

go:
  - 1.8.x
  - 1.9.x
  - master

before_install:
  - go get -u -v github.com/campoy/embedmd
  - embedmd -d *.md

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)